Repository arduino/setup-task, pull requests merged in 2021-12, with the labels that each got.

#258 Print installed Task version
  dist/index.js
  src/installer.ts
Labels: type: enhancement, topic: code

#259 Ignore node_modules on fixers and linters
  .codespellrc
  .markdownlintignore
  Taskfile.yml
  package-lock.json
Labels: type: imperfection, topic: infrastructure

#280 Use major version ref of `carlosperate/download-file-action`
  .github/workflows/check-npm.yml
  .github/workflows/check-tsconfig.yml
  .github/workflows/sync-labels.yml
Labels: type: enhancement, topic: infrastructure
